# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SSRLabTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SSRLabTest

pod 'AlamofireNetworkActivityLogger'
pod 'Alamofire'
pod 'NVActivityIndicatorView'
pod 'GoogleMaps'

end
